# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [master] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      env:
        GIT_NAME: hustchenshu
        GIT_EMAIL: ${{ secrets.GT_MAIL }}
        REPO: github.com/hustchenshu/hustchenshu.github.io
        GH_TOKEN: ${{ secrets.GT_TOKEN }}
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git remote set-url upstream https://$GH_TOKEN:x-oauth-basic@github.com/$GIT_NAME/$REPO.git
        git remote set-url origin https://$GH_TOKEN:x-oauth-basic@github.com/$GIT_NAME/$REPO.git
        git branch -m main
        hexo clean
        hexo d
